version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: inventory_app
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: inventory_db
    environment:
      MYSQL_DATABASE: inventory
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: inventory_user
      MYSQL_PASSWORD: inventory_pass
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql

  wordpress:
    image: wordpress:latest
    container_name: inventory_wp
    ports:
      - "8080:80" # 🌐 Accederás al admin por http://localhost:8080
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: inventory_user
      WORDPRESS_DB_PASSWORD: inventory_pass
      WORDPRESS_DB_NAME: inventory
    volumes:
      - ./wp-content:/var/www/html/wp-content # 📌 Aquí irán tus plugins
    depends_on:
      - db

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: inventory_phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      - db

volumes:
  dbdata:
