version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: inventory_app
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: inventory_db
    environment:
      MYSQL_DATABASE: inventory
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: inventory_user
      MYSQL_PASSWORD: inventory_pass
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata:
